server:
  port: 9091
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: root
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
