server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
spring:
  main:
    allow-circular-references: true
  application:
    name: discovery-server
client:
  username: eureka
  password: password

