server:
  port: 0
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: root
  application:
    name: inventory-service
  jpa:
    hibernate:
      ddl-auto: create-drop
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

